### ISSUE TITLE
Possible to specify name attribute of file?

### ISSUE THREAD

**Issue by realcheese** [charliekassel/vuejs-uploader#10]
Works great, but is it possible to set the name attribute on the file input? I'd like to use several uploaders on a page. After the upload, I'm having trouble figuring out which file came from which uploader.

**Comment by charliekassel** [comment]
I would either have separate endpoints on the server for different upload types, or have separate methods in your component using the uploader - each could send an extra identifying post var.

**Comment by realcheese** [comment]
Thank you for the reply. Much appreciated.
