### ISSUE TITLE
Response Handler

### ISSUE THREAD

**Issue by mcanzerini** [charliekassel/vuejs-uploader#5]
Hi there,

Thanks for your great job ! 

My question is : I need to access to the response data after my file upload request. (multiple = false)

Is there a way to access to this response ( like the error handler but when nothing goes wrong ) ?

Thanks guys

MC

**Comment by charliekassel** [comment]
Hi, yeah it emits a `fileUploaded` event with the response data.
https://github.com/charliekassel/vuejs-uploader/blob/master/src/components/Uploader.vue#L272-L275
or here if you're using the multipart upload option:
https://github.com/charliekassel/vuejs-uploader/blob/master/src/components/Uploader.vue#L333-L336

**Comment by mcanzerini** [comment]
Thanks for your quick answer 👍
