### ISSUE TITLE
Fatal Error Unable to create lock file: Bad file descriptor (9)

### ISSUE THREAD

**Issue by MateuszFlisikowski** [charliekassel/vuejs-uploader#6]
Hi, when a try to run php server i got that message "Fatal Error Unable to create lock file: Bad file descriptor (9)", I'm not php dev, can you help me?

**Comment by charliekassel** [comment]
how are you trying to run it?
what do you get from `php -v`?

**Comment by MateuszFlisikowski** [comment]
I'm connected to the server using putty ssh. Output:

[******************* 15:08 ~/public_html/server/php]$ php7-cli -v
PHP 7.0.26 (cli) (built: Dec  4 2017 09:10:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.9, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.26, Copyright (c) 1999-2017, by Zend Technologies

**Comment by charliekassel** [comment]
oh, this is for running a local server on your development machine.

**Comment by MateuszFlisikowski** [comment]
ok
