### ISSUE TITLE
Upload gets stuck after uploading the first part

### ISSUE THREAD

**Issue by abhijeetvhotkar** [charliekassel/vuejs-uploader#7]
Hi @charliekassel 

I'm trying to clone the repo and get it running locally.

Steps:
1. Clone the repo
2. npm install
3. start the php server
4. rm -rf dist/* && node build/build.js
5. node build/dev-server.js
6. Upload a video in the first uploader box with file size 10mB
7. Only the first part gets uploaded.

![screen shot 2018-01-31 at 11 27 39 am](https://user-images.githubusercontent.com/22862716/35634490-cc8c0966-0679-11e8-85ea-3db3800a8036.png)

Thanking you in advance for your help.

**Comment by charliekassel** [comment]
Are you uploading to a server?
The `remainingParts` response should actually be optional.

**Comment by abhijeetvhotkar** [comment]
Yes I'm uploading to the Demo php server as explained in the documentation.

**Comment by charliekassel** [comment]
Looks like I need to update the demo server.
remainingParts should be namespaced under `meta` now.
Try adding that here: https://github.com/charliekassel/vuejs-uploader/blob/master/server/php/index.php#L209

**Comment by abhijeetvhotkar** [comment]
Solves the issue.

Thanks @charliekassel

**Comment by charliekassel** [comment]
I'll keep this open as a reminder for me to fix.
